### ISSUE TITLE
How to show Stock Availability in Manage Products Grid ?

### ISSUE THREAD

**Issue by abrawat16** [magento-hackathon/GridControl#14]
Hi ,
First of all i would i like to thank you for developing such an awesome extension. This extension is working fine with my all stores , However i am having trouble to add "Stock Availability" section in Manage Products grid. I want to show "In stock / Out of Stock" under "Stock Availability" header in Manage Products grid.
Can you please guide which node do i need to place inside gridcontrol.xml file ? 
Thanks

**Comment by Schrank** [comment]
I can't check it at the moment, but you have to join the stock items into the collection and than add is_in_stock to the grid, like this:

    <add>
        <header>Availablility</header>
        <type>text</type>
        <index>is_in_stock</index>
        <joinField>is_in_stock|cataloginventory/stock_item|qty|product_id=entity_id|{{table}}.stock_id=1|left</joinField>
    </add>

**Comment by abrawat16** [comment]
Hi ,

After adding your code now i am getting only numbers under Availablity column, but i am not getting "In Stock" / "Out of Stock " text , Please find below link where i have added xml code  , and Please find attached screenshot file as well , Here i have marked Availability Column in Dark Blue Color which is last column.

 gridcontrol.xml  code :- https://gist.github.com/abrawat16/b90e1abd09d0b786676d 
Please see  line no 48 to 55 

![stock](https://cloud.githubusercontent.com/assets/4210319/10342350/3e4a5cea-6d36-11e5-9e0e-13c40ad8db1f.png)

Thanks

**Comment by Schrank** [comment]
Please read the README.

You can try like 

                 <options>
                        <option_a>
                            <key>1</key>
                            <value>Active</value>
                        </option_a>

                        <option_b>
                            <key>2</key>
                            <value>Inactive</value>
                        </option_b>
                    </options>

I don't think that source models are supported yet, if it is (read the code) you can use \Mage_CatalogInventory_Model_Source_Stock if it is not, you have to do it by hand.

You can implement Source model usage and PR it! :-)

**Comment by Schrank** [comment]
Please read the README.

You can try like 

                 <options>
                        <option_a>
                            <key>1</key>
                            <value>Active</value>
                        </option_a>

                        <option_b>
                            <key>2</key>
                            <value>Inactive</value>
                        </option_b>
                    </options>

I don't think that source models are supported yet, if it is (read the code) you can use \Mage_CatalogInventory_Model_Source_Stock if it is not, you have to do it by hand.

You can implement Source model usage and PR it! :-)

**Comment by Schrank** [comment]
Please read the README.

You can try like 

                 <options>
                        <option_a>
                            <key>1</key>
                            <value>Active</value>
                        </option_a>

                        <option_b>
                            <key>2</key>
                            <value>Inactive</value>
                        </option_b>
                    </options>

I don't think that source models are supported yet, if it is (read the code) you can use \Mage_CatalogInventory_Model_Source_Stock if it is not, you have to do it by hand.

You can implement Source model usage and PR it! :-)

**Comment by Schrank** [comment]
Please read the README.

You can try like 

                 <options>
                        <option_a>
                            <key>1</key>
                            <value>Active</value>
                        </option_a>

                        <option_b>
                            <key>2</key>
                            <value>Inactive</value>
                        </option_b>
                    </options>

I don't think that source models are supported yet, if it is (read the code) you can use \Mage_CatalogInventory_Model_Source_Stock if it is not, you have to do it by hand.

You can implement Source model usage and PR it! :-)
