### ISSUE TITLE
compatibility with patch SUPEE-6788

### ISSUE THREAD

**Issue by danielepennati** [magento-hackathon/GridControl#15]
Hello,
we are using GridControl on several website and I'd like to know if it is compatible with the new SUPEE-6788 Magento Patch that introduce some Backward Compatibility Issue: https://info2.magento.com/rs/318-XBX-392/images/SUPEE-6788-Technical%20Details.pdf

Thanks
Daniele Pennati

**Comment by Schrank** [comment]
It doesn't have any admin controller and it doesn't use any directives or variables in CMS block rendering, therefore I would say, yes it is compatible.

**Comment by danielepennati** [comment]
thanks!
