### ISSUE TITLE
Having difficulty configuring options for custom attributes

### ISSUE THREAD

**Issue by cdalsass** [magento-hackathon/GridControl#20]
Is it possible to configure options for custom attributes with this module? I've tried this, but to no avail.

          <sample_type>
                <add>
                <header>Sample Type</header>
                <index>sample_type</index>
                <type>options</type>
                <options>catalog/product/sample_type::getOptionArray</options>
                </add>
            </sample_type>

Great module BTW!

Charlie

**Comment by Schrank** [comment]
Yes it is.

https://github.com/magento-hackathon/GridControl/blob/master/src/app/code/community/FireGento/GridControl/Model/Processor.php#L109-L119

Why are there two `/` in the model name?
> catalog/product/sample_type

**Comment by cdalsass** [comment]
Thanks so much Schrank. 

I removed the additional /, following the syntax of your example, by prepending "product_" to attribute name, but am still having problems getting the options list of a custom attribute. My current syntax is as follows. 

Any further ideas (I can also move this question to StackOverflow if you prefer)?

p.s. I also added print statements to those lines, and the (sample) working output is exactly like the custom attribute output. 

`<sample_type>
    <add>
        <header>Sample Type</header>
        <index>sample_type</index>
        <type>options</type>
        <options>catalog/product_sample_type::getOptionArray</options>
    </add>
    <after>price</after>
</sample_type>`

**Comment by Schrank** [comment]
<small>If you either prepend your code with four spaces or three `````, github won't eat your line breaks ;-)</small>

We have a missunderstanding. You have to pass a class::method to use this syntax. So you have to create a class which more or less does only:

    $name='whatever_your_attribute_name';
    $attributeInfo = Mage::getResourceModel('eav/entity_attribute_collection')->setCodeFilter($name)->getFirstItem();
    $attributeId = $attributeInfo->getAttributeId();
    $attribute = Mage::getModel('catalog/resource_eav_attribute')->load($attributeId);
    $attributeOptions = $attribute ->getSource()->getAllOptions(false); 

[Source](http://stackoverflow.com/a/19564842/1480397)

**Comment by cdalsass** [comment]
Yes, this makes sense. I am missing that class for custom attributes. Do you want this documented somewhere? Maybe a question on StackOverflow?

p.s. Appreciate the Github tip.

**Comment by Schrank** [comment]
A PR to better document it on the readme will be greatly appreciated!
