### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by AydinHassan** [magento-hackathon/GridControl#23]
Hi - is it possible to tag a version of this library? I don't want to have to rely on `dev-master`.

**Comment by borriglione** [comment]
I would prefer to have release tags too.

But @AydinHassan you can refer to a special commit state in composer too.

"firegento/gridcontrol": "dev-master#d3e03fdd83b8e630c7e5d3f9dd8bf9c196f4a62f"

(d3e03fdd83b8e630c7e5d3f9dd8bf9c196f4a62f is the latest one now)

**Comment by AydinHassan** [comment]
@borriglione yep, however, the Composer docs specifically state that it is not a good idea to rely on this behaviour. 

> Note: While this is convenient at times, it should not be how you use packages in the long term because it comes with a technical limitation. The composer.json metadata will still be read from the branch name you specify before the hash. Because of that in some cases it will not be a practical workaround, and you should always try to switch to tagged releases as soon as you can.

**Comment by Schrank** [comment]
Have fun :)

**Comment by AydinHassan** [comment]
@Schrank great - thanks!
