### ISSUE TITLE
Ordered Qty in Product Grid

### ISSUE THREAD

**Issue by Raphomee** [magento-hackathon/GridControl#26]
Hi,

dont know how to add overall ordered qty in product grid.
Can you give me advise ?
column stays empty, probably I need a join to get this data?

###
        <productGrid>
            
            <ordered_qty>
                
                <add>
                    
                    <header>Qty ordered</header>
                    
                    <type>text</type>
                    
                    <index>ordered_qty</index>
                </add>
                
                <after>price</after>
            </ordered_qty>
        </productGrid>
###

Kind regards

**Comment by Schrank** [comment]
Hi @Raphomee I don't think this is easy possible.

Without join you can only include which is already there. This column doesn't exist (as you said) therefore you need either join it from the reports (somewhere, no clue where it can be got) or you can make a join? or subselect into the order_item table.

I'm not sure this is possible with this extension.

**Comment by Raphomee** [comment]
Hi @Schrank 
Thanks.
I'll check if I find out how to get this field.
This extension is able to use getCollection()->join(), getCollection()->joinField() and getCollection()->joinAttribute() so it should be possible.

**Comment by Schrank** [comment]
Good luck!

We would love to have this in the examples on the readme, so feel free to make a PR!
